/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package lv.n3o.swapper2;

public final class R {
    public static final class array {
        public static final int swappiness=0x7f060002;
        public static final int swappiness_int=0x7f060003;
        public static final int swapsize=0x7f060000;
        public static final int swapsize_int=0x7f060001;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int LogText=0x7f070006;
        public static final int ScrollView01=0x7f070005;
        public static final int ScrollView02=0x7f070000;
        public static final int SwapOff=0x7f070004;
        public static final int SwapOn_32=0x7f070003;
        public static final int TableLayout01=0x7f070001;
        public static final int TableRow01=0x7f070002;
    }
    public static final class layout {
        public static final int main=0x7f030000;
    }
    public static final class string {
        public static final int app_name=0x7f050000;
        public static final int startup_text=0x7f050001;
    }
    public static final class xml {
        public static final int preferences=0x7f040000;
    }
}
